import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' })
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').first().click();
  await page.getByRole('listbox').getByText('Admin').click();
  await page.locator('form').getByText('Admin').click();
  await page.getByRole('option', { name: 'ESS' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('k');
  await page.getByRole('option', { name: 'Ranga Akunuri' }).click();
  await page.getByText('-- Select --').click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('abntg');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('admin123');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('admin123');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers');
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('link', { name: 'Add Employee' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Sagar');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('samarth');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('Reddy');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Samarth');
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('Samarth');
  await page.getByRole('textbox', { name: 'Middle Name' }).dblclick();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Sreemath');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Shreemath');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Shreemanth');
  await page.locator('div').filter({ hasText: /^Employee Id$/ }).first().click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('0419');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/218');
  await page.locator('.oxd-icon.bi-caret-down-fill.oxd-select-text--arrow').first().click();
  await page.getByRole('option', { name: 'Indian' }).click();
  await page.locator('div:nth-child(2) > .oxd-input-group > div:nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
  await page.getByRole('option', { name: 'Single' }).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).fill('20/12/2000');
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).fill('12/2026/20');
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).click();
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).fill('12/2026-20');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'mm-yyyy-dd' }).nth(1).fill('12-2026-20');
  await page.getByText('Male', { exact: true }).click();
  await page.locator('div:nth-child(7) > .oxd-grid-3 > div > .oxd-input-group > div:nth-child(2) > .oxd-input').click();
  await page.locator('.oxd-input.oxd-input--focus').fill('No');
  await page.locator('.oxd-icon.bi-check').first().click();
  await page.locator('form').filter({ hasText: 'Employee Full' }).getByRole('button').click();.click();
  await page.getByRole('link', { name: 'PIM' }).click();
  await page.getByRole('link', { name: 'Leave' }).click();
  await page.getByRole('link', { name: 'Time' }).click();
  await page.getByRole('link', { name: 'My Info' }).click();
  await page.getByRole('link', { name: 'Dashboard' }).click();
});